add get taters, bootstrap changes

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -1,44 +1,38 @@
 #!/bin/bash
 
-# Check if Docker is installed
+echo "Checking dependencies..."
+
+echo "Checking Docker..."
 if ! command -v docker &>/dev/null; then
-  echo "Docker not found. Installing Docker..."
-  # Install Docker
-  # Add your installation command here
-  # Check for and install docker
-  echo "Docker installed successfully."
-else
-  echo "Docker is already installed."
-fi
-
-# Check if Terraform is installed
-if ! command -v terraform &>/dev/null; then
-  echo "Terraform not found. Installing Terraform..."
-
-  echo "Terraform installed successfully."
-else
-  echo "Terraform is already installed."
-fi
-
-# Check if Golang is installed
-if ! command -v go &>/dev/null; then
-  echo "Golang not found. Installing Golang..."
-  # Install Golang
-  # Add your installation command here
-  echo "Golang installed successfully."
-else
-  echo "Golang is already installed."
-fi
-
-# Check if the localstack container is running
-if ! docker ps | grep -q localstack; then
-  echo "Localstack container not found. Please run 'docker compose up'"
+  echo "Docker not found. Please install Docker."
   exit 1
+else
+  echo "Docker is installed."
+fi
+
+echo "Checking Golang..."
+if ! command -v go &>/dev/null; then
+  echo "Golang not found. Please install Golang."
+else
+  echo "Golang is installed."
+fi
+
+echo "Checking if Localstack container is running..."
+if ! docker ps | grep -q localstack; then
+  echo "Localstack container not found. Starting Localstack..."
+  docker compose up -d localstack
+  echo "Localstack container started."
 else
   echo "Localstack container is running, continuing..."
 fi
 
-terraform -chdir=./infrastructure init -input=false
-terraform -chdir=./infrastructure apply -input=false -auto-approve
+echo "Running Terraform..."
+docker run --rm --net=host -v "$(pwd)/infrastructure:/app" -w /app hashicorp/terraform:latest init -input=false
+docker run --rm --net=host -v "$(pwd)/infrastructure:/app" -w /app hashicorp/terraform:latest apply -input=false -auto-approve
+echo "Terraform complete!"
+
+echo "Spinning down Localstack..."
+docker compose down localstack
+echo "Localstack spun down."
 
 echo "Bootstrap complete!"
